version: "3"

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres-as-local-db
    image: postgres-setup-docker_postgres
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=POSTGRES_DB
      - POSTGRES_PASSWORD=password
      # - POSTGRES_USER=root
  
  pgadmin:
    build:
      context: ./pgAdmin
    container_name: pgAdmin-for-local
    ports:
      - '85:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=password