version: "3"

services:

  django-api:
    build:
      context: ./Django
    container_name: postgres-django-api
    ports:
      - '8000:8000'
    
  postgres:
    build:
      context: ./postgres
    container_name: postgres-as-local-db
    volumes:
      # volume
      - ./postgres/data/:/var/lib/postgresql/data
      # init data
      - ./postgres/init-data:/docker-entrypoint-initdb.d
      - ./postgres/init-data/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=POSTGRES_DB
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=shin
  
  pgadmin:
    build:
      context: ./pgAdmin
    container_name: pgAdmin-for-local
    ports:
      - '85:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=password