#
# - get inside the container
# docker exec -it postgres-as-local-db bash
#
# - get server info
# docker inspect CONTEINER_NAME -f "{{json .NetworkSettings.Networks }}"
# docker inspect postgres-as-local-db -f "{{json .NetworkSettings.Networks }}"
#

FROM postgres:13.0-alpine