#
# https://towardsdatascience.com/local-development-set-up-of-postgresql-with-docker-c022632f13ea
#
# - get inside the container
# docker exec -it postgres-as-local-db bash
#
# - postgres
# psql -h localhost -U postgres
#
# - get server info
# docker inspect CONTEINER_NAME -f "{{json .NetworkSettings.Networks }}"
# docker inspect postgres-as-local-db -f "{{json .NetworkSettings.Networks }}"
#


FROM postgres:13.0-alpine